CREATE DATABASE customer_behaviour;
USE customer_behaviour;

-- Q1. What is the total revenue generated by male vs. female customers?

SELECT gender,SUM(purchase_amount) AS Total_Revenue
FROM customer
GROUP BY gender;

-- Q2.Which customers used a discount but still spent more than the average purchase amount?
 SELECT customer_id,purchase_amount
 FROM customer
 WHERE discount_applied= 'Yes' AND purchase_amount>=(SELECT AVG(purchase_amount)
 FROM customer);
 
 -- Q3.What are the top 5 products with the highest average review rating?
 
 SELECT item_purchased,ROUND(AVG(review_rating),2) AS highest_rating
 FROM customer
 GROUP BY item_purchased
 ORDER BY highest_rating DESC LIMIT 5;
 
 -- Q4. Compare the average purchase amounts between standard and Express shipping.
 
 SELECT shipping_type,ROUND(AVG(purchase_amount),2)
 FROM customer
 WHERE shipping_type IN ('Standard','Express')
 GROUP BY shipping_type;
 
 -- Q5. Do subscribed customers spend more? Compare average spend and total revenue \\
 -- between subscribers and non-subscribers
  
  SELECT subscription_status,SUM(purchase_amount)AS total_revenue,ROUND(AVG(purchase_amount),2) AS avg_spent,
  COUNT(customer_id) AS Total_customers
  FROM customer 
  GROUP BY subscription_status;
  
  -- Q6.Which 5 products have the highest percentage of purchases with discouts applied?
  
 SELECT item_purchased,
 ROUND(SUM(CASE WHEN discount_applied= 'Yes' THEN 1 ELSE 0 END )/COUNT(*)*100,2)  AS discount_rate
 FROM customer
 GROUP BY item_purchased
 ORDER BY discount_rate DESC
 LIMIT 5;
 
 -- Q7. Segment customers into New , Returning ,Loyal based on their total number of previous purchases
 -- and show the count of each segment.
 
 WITH customer_type AS (
 SELECT customer_id,previous_purchases,
 CASE
     WHEN previous_purchases = 1 THEN 'New'
     WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
     ELSE 'Loyal'
     END AS customer_segment
FROM customer)
SELECT customer_segment, COUNT(*) AS 'Number of Customers'
FROM customer_type
GROUP BY customer_segment;

-- Q8. Are customers who are repeat buyers(more than 5 purchases) also likely to subscribe?
SELECT subscription_status,
COUNT(customer_id) AS repeat_buyers
FROM customer
WHERE previous_purchases>5
GROUP BY subscription_status;

-- Q9.What is the revenue contribution of each age group?
SELECT age_group,SUM(purchase_amount) AS revenue_contribution
FROM customer
GROUP BY age_group;


SELECT * FROM customer



